sudo: required
services:
  - docker

before_install:
  - docker_build -t lelouchdocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lelouchdocker/react-test npm test

after_success:
  - docker build -t lelouchdocker/multi-client ./client
  - docker build -t lelouchdocker/multi-nginx ./nginx
  - docker build -t lelouchdocker/multi-server ./server
  - docker build -t lelouchdocker/multi-worker ./worker
  # login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "#DOCKER_ID" --password-stdin
  # take those images and push to docker hub
  - docker push lelouchdocker/multi-client
  - docker push lelouchdocker/multi-nginx
  - docker push lelouchdocker/multi-server
  - docker push lelouchdocker/multi-worker